Develop
Gidrosliv/java-explore-with-me pull request #5
Opened 2022-10-05 16:55 UTC by Gidrosliv

2022-10-14 12:50 UTC, Frilock requested changes
Добрый день, комментарии в коде. Будут вопросы пишите в Slack. Жду новую иттерацию.

2022-10-14 12:50 UTC, Frilock commented on main-server/pom.xml
> +            <dependency>
Съехало форматирование, нужно поправить.

2022-10-14 12:50 UTC, Frilock commented on main-server/pom.xml
> +            <version>2.2</version>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/controllers/PublicController.java
> +    URI uri;
Нужно добавить модификаторы доступа к полям.

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/dto/category/NewCategoryDto.java
> +    String name;
нужно добавить модификатор доступа к полям, проверьте в других местах. Кроме того, сейчас не особо рекомендуется использовать Data и Builder совместно. https://habr.com/ru/company/haulmont/blog/564682/

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/mapper/category/CategoryMapper.java
> +@Component
Зачем данный класс делать компонентом спринга?

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/mapper/compilation/CompilationMapper.java
> +@Component
На мой взгляд, классы маперы не должны быть компонентами спринга. У Вас тут статические методы, в классе другие бины не инжектятся. Проверьте другие места

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/mapper/event/EventMapper.java
> +        eventShortDto.setViews(event.getViews()); //todo
Давайте todo уберем из кода. Для меня это сразу подсказка, что работа не закончена

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/model/category/Category.java
> +    @Column(name = "name", nullable = false)
Вы в своих скриптах задаете размерность полей. В аннотации Column эту размерность тоже лучше указывать, поскольку база не всегда накатывается скриптами, которые лежат в приложении, поэтому не всегда есть возможность узнать размерность поля. Проверьте в других местах тоже

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/model/event/EventStatus.java
> +
лишняя пустая строка

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/model/request/RequestStatus.java
> +    CONFIRMED, REJECTED, CANCELED
Давайте приведем все к одному виду, либо все в одну строчку, либо одна запись на каждую

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/repository/compilation/CompilationRepository.java
> +@Repository
Над интерфейсами можно не ставить аннотацию для спрингового компонента, главное чтоб она стояла над классами реализациями

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/service/request/RequestServiceImpl.java
> +        if (event.getStatus().name().equals(RequestStatus.APPROVED.name()) && event.getStatus().name().equals(RequestStatus.CANCELED.name())) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее.
Кроме того, не знаю предлагали ли Вам до этого или нет, но советую поставить себе в IDEA плагин sonarlint, это статический анализатор кода, он подскажет ряд хороших практик и возможные проблемные места.
Кроме того, хочу еще оставить такой общий комментарий: вот смотрите Вы тут используете стандартный equals. event.get..().equals ... смотрите, если event.get... вернет null, то будет NPE, нужно либо быть уверенным, что будет возвращено какое то значение, либо использовать null safe equals - Objects.equals(o1, o2)

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/service/user/UserServiceImpl.java
> +        if (newUserRequest.getName() == null || newUserRequest.getEmail() == null) {
Какая то слабая валидация, на мой взгляд. По поводу наименования - может прийти "" и Ваша проверка не сработает. Предлагаю использовать - Objects.isBlack / Objects.isNotBlack. А для Email вообще нужно какое то регулярное выражение использовать.

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/service/user/UserServiceImpl.java
> +
лишняя пустая строчка

2022-10-14 12:50 UTC, Frilock commented on main-server/src/main/resources/application.properties
> +#spring.datasource.url=${SPRING_DATASOURCE_URL}
Закоментированный код лучше не оставлять в приложении. В истории гита все равно будут изменения сохранены, а так вы потом забудете зачем его закоментировали

2022-10-14 12:50 UTC, Frilock commented on stat-server/src/main/java/ru/practicum/app/model/HitsRequest.java
> +
Лишняя пустая строка

2022-10-14 12:50 UTC, Frilock commented on stat-server/src/main/java/ru/practicum/app/service/StatisticService.java
> +        if (!start.isEmpty() && !end.isEmpty()) {
Аналогичный комментарий который я оставлял выше. А если start == null? Получите NPE. Проверяйте поля с использование Objects.isBlank

2022-10-14 12:50 UTC, Frilock commented on stat-server/src/main/java/ru/practicum/app/service/StatisticService.java
> +public class StatisticService {
Кроме того, для слоя сервисов хочется увидеть unit тесты, поскольку свой код нужно тестировать самим тоже. Знаю что это не обязательное задание у Вас, но я бы порекомендовал их добавить.

2022-10-15 15:54 UTC, Gidrosliv commented on main-server/pom.xml
> +            <version>2.2</version>
Хорошее замечание, но меня поправил Владимир, когда возникли проблемы с тестами, что конфигурационные файлы должны соответствовать предложенному шаблону.

2022-10-15 15:56 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/mapper/category/CategoryMapper.java
> +@Component
Потому что данный класс является компонентом. Если убрать эту аннотацию, я не соберу проект.

2022-10-15 15:56 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/mapper/compilation/CompilationMapper.java
> +@Component
ответил выше

2022-10-15 16:04 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/model/category/Category.java
> +    @Column(name = "name", nullable = false)
исправил

2022-10-15 16:05 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/repository/compilation/CompilationRepository.java
> +@Repository
исправил

2022-10-15 16:09 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/service/request/RequestServiceImpl.java
> +        if (event.getStatus().name().equals(RequestStatus.APPROVED.name()) && event.getStatus().name().equals(RequestStatus.CANCELED.name())) {
Поля статус у евента обязательные поэтому нулл там быть не может. А если уж не найдется эвент, то тоже выпадет исключение.

2022-10-15 16:36 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/service/user/UserServiceImpl.java
> +        if (newUserRequest.getName() == null || newUserRequest.getEmail() == null) {
исправил

2022-10-15 16:36 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/service/user/UserServiceImpl.java
> +
исправил

2022-10-15 16:40 UTC, Gidrosliv commented on main-server/src/main/resources/application.properties
> +#spring.datasource.url=${SPRING_DATASOURCE_URL}
исправил

2022-10-15 16:40 UTC, Gidrosliv commented on stat-server/src/main/java/ru/practicum/app/model/HitsRequest.java
> +
исправил

2022-10-15 16:41 UTC, Gidrosliv commented on stat-server/src/main/java/ru/practicum/app/service/StatisticService.java
> +public class StatisticService {
Если быстро сдам, то займусь тестами.

2022-10-15 16:42 UTC, Gidrosliv commented on stat-server/src/main/java/ru/practicum/app/service/StatisticService.java
> +        if (!start.isEmpty() && !end.isEmpty()) {
исправил

2022-10-15 16:51 UTC, Gidrosliv commented on main-server/pom.xml
> +            <dependency>
исправил

2022-10-15 16:52 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/controllers/PublicController.java
> +    URI uri;
исправил

2022-10-15 16:52 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/dto/category/NewCategoryDto.java
> +    String name;
исправил

2022-10-15 20:39 UTC, Frilock requested changes
Добрый вечер. Нужно разобраться с вопросом с бинами.

Давайте разберемся. Почему данный класс является компонентом? Это простой публичный класс с статическими методами. Там где вы его инжектите через конструктор или просто через Autowired Вы можете просто использовать статические методы данного класса. 
Пришлите мне ошибку, которую Вы получаете при компиляции или пришлите работу заново с ответом, поскольку Вы прислали архив без кода своих модулей.

2022-10-15 20:39 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/mapper/category/CategoryMapper.java
> +@Component
Давайте разберемся. Почему данный класс является компонентом? Это простой публичный класс с статическими методами. Там где вы его инжектите через конструктор или просто через Autowired Вы можете просто использовать статические методы данного класса. 
Пришлите мне ошибку, которую Вы получаете при компиляции или пришлите работу заново с ответом, поскольку Вы прислали архив без кода своих модулей.

2022-10-15 20:39 UTC, Frilock commented on main-server/pom.xml
> +            <version>2.2</version>
Странно, мне только вчера дипломную работу присылали с исправленным таким замечанием и зелеными тестами. В целом если Вы сами не хотите с этим разобраться это Ок, я не заставляю, просто на мой взгляд, это было бы правильнее =)

2022-10-15 21:03 UTC, Gidrosliv commented on main-server/src/main/java/ru/practicum/app/mapper/category/CategoryMapper.java
> +@Component
исправил

2022-10-17 06:22 UTC, Frilock approved these changes
Доброе утро. Работу принял, но есть ряд нюансов, которые хотелось бы чтобы вы в дальнейшем поправили. 
1. Разобрались до конца с pom файлами (это правда хорошая практика)
2. Какая то вакханалия с модификаторами, где то они есть, где то нет. Я Вам оставлял общий комментарий на эту тему, но часть мест не поправлено (допускаю, что это из за отката версии)

2022-10-17 06:22 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/dto/event/EventShortDto.java
> +    UserShortDto initiator;
Почему тут нет модификатора?

2022-10-17 06:22 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/model/event/AdminUpdateEventRequest.java
> +    Integer eventId;
Почему для данного класса отсутствуют модификаторы? Я вроде Вам оставлял комментарий, Вы сказали что поправили.

2022-10-17 06:22 UTC, Frilock commented on main-server/src/main/java/ru/practicum/app/model/event/UpdateEventRequest.java
> +/***
Такие комментарии не нужны, в целом по названию класса понятно, для чего он

2022-10-22 14:05 UTC, merged